lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', index, name='home'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

teachers/urls.py
from django.urls import path

from .views import ListTeacherView
from .views import UpdateTeacherView
from .views import CreateTeacherView
from .views import DeleteTeacherView
from .views import DetailTeacherView

app_name = 'teachers'

urlpatterns = [
    path('', ListTeacherView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateTeacherView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailTeacherView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteTeacherView.as_view(), name='delete')
]

teachers/models.py
import datetime
from random import randint

from django.db import models
from faker import Faker


from core.models import PersonModel

class Teacher(PersonModel):
    salary = models.PositiveIntegerField(default=10_000)

    class Meta:
        db_table = 'teachers'

    def __str__(self):
        return f'{self.first_name} {self.last_name} (${self.salary})'


    @classmethod
    def _generate(cls):
        teacher = super()._generate()
        teacher.salary = randint(10_000, 50_000)
        teacher.save()

teachers/forms.py
from django import forms
from django_filters import FilterSet
from teachers.models import Teacher


class CreateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'salary'
        ]
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }


class UpdateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'salary'
        ]


class TeacherFilterForm(FilterSet):
    class Meta:
        model = Teacher
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith']
        }

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from teachers.forms import CreateTeacherForm, UpdateTeacherForm, TeacherFilterForm
from django.views.generic import DetailView, DeleteView, ListView, UpdateView, CreateView
from teachers.models import Teacher


class ListTeacherView(ListView):
    model = Teacher
    template_name = 'teachers/list.html'

    def get_queryset(self):
        teachers = Teacher.objects.all().order_by('birthday')
        filter_form = TeacherFilterForm(data=self.request.GET, queryset=teachers)
        return filter_form


class CreateTeacherView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = CreateTeacherForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/create.html'


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = UpdateTeacherForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/update.html'


class DetailTeacherView(LoginRequiredMixin, DetailView):
    model = Teacher
    template_name = 'teachers/detail.html'


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = 'teachers/delete.html'
    success_url = reverse_lazy('teachers:list')

teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create teacher{% endblock %}

{% block content %}
        <div class='row'>
            <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="text-center">
                        <input class="btn btn-outline-success" type="submit" value="Create">
                        <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                    </div>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
{% endblock %}

teachers/templates/teachers/delete.html
{% extends 'base.html' %}

{% block title %}Delete teacher{% endblock %}

{% block content %}
    <div class='row'>
            <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                         <p>Do you want to delete teacher <strong>{{ teacher.first_name }} {{ teacher.last_name }}</strong>?</p>
                        <input class="btn btn-outline-success" type="submit" value = 'Agree'>
                        <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                    </div>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
{% endblock %}

teachers/templates/teachers/detail.html
{% extends 'base.html' %}

{% block title %}Teacher details{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col align-self-center">
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">{{ teacher.first_name }}{{ teacher.last_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ teacher.birthday|date:'d M Y' }}</h6>
                <p class="card-text">salary: {{ teacher.salary }}</p>
                <div class="text-center">
                    <a class="btn btn-outline-primary" href="{% url 'teachers:update' teacher.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
              </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Teachers list{% endblock %}

{% block content %}
    <div class="row">
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        Search
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                     data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <div class="col-3"></div>
                        <div class="col">
                            <form method="get">
                                {{ object_list.form|crispy }}
                                <input class="btn btn-outline-success" type="submit" value="Search"><br>
                            </form>
                        </div>
                        <div class="col-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
            <tr class="text-center">
                <th></th>
                <th>First name</th>
                <th>Last name</th>
                <th>Birthday</th>
                <th>Salary</th>
                {% if user.is_authenticated %}
                    <th><i class="bi bi-pencil-square"></i></th>
                    <th><i class="bi bi-trash3"></i></th>
                {% endif %}
            </tr>
            <thead>
            <tbody>
            {% for teacher in object_list.qs %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'teachers:detail' teacher.pk %}">{{ teacher.first_name }}</a></td>
                    {% else %}
                        <td>{{ teacher.first_name }}</td>
                    {% endif %}
                    <td>{{ teacher.last_name }}</td>
                    <td class="text-center">{{ teacher.birthday|date:'d M Y(l)'}}</td>
                    <td class="text-center">{{ teacher.salary }}</td>
                    {% if user.is_authenticated %}
                        <td class="text-center"><a class="btn btn-outline-primary btn-sm"
                                                   href="{% url 'teachers:update' teacher.pk %}">Edit</a></td>
                        <td class="text-center"><a class="btn btn-outline-danger btn-sm"
                                                   href="{% url 'teachers:delete' teacher.pk %}">Remove</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
            </table>
   </div>
{% endblock %}

teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Teacher update{% endblock %}

{% block content %}
        <div class='row'>
            <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="text-center">
                        <input class="btn btn-outline-success" type="submit" value="Update">
                        <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                    </div>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
{% endblock %}