accounts/urls.py
from django.urls import path

from .views import AccountRegisterView, profile_view, UpdateProfileView
from .views import AccountLoginview
from .views import AccountLogoutView



app_name = 'accounts'

urlpatterns = [
    path('register/', AccountRegisterView.as_view(), name='register'),
    path('login/', AccountLoginview.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/update', UpdateProfileView.as_view(), name='profile_update'),
]

courses/urls.py
from django.urls import path

from .views import ListCourseView
from .views import CreateCourseView
from .views import UpdateCourserView
from .views import DetailCourseView
from .views import DeleteCourseView

app_name = 'courses'

urlpatterns = [
    path('', ListCourseView.as_view(), name='list'),
    path('create/', CreateCourseView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateCourserView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailCourseView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteCourseView.as_view(), name='delete'),

]

groups/urls.py
from django.urls import path

from .views import ListGroupVIew
from .views import CreateGroupView
from .views import UpdateGroupView
from .views import DetailGroupView
from .views import DeleteGroupView

app_name = 'groups'

urlpatterns = [
    path('', ListGroupVIew.as_view(), name='list'),
    path('create/', CreateGroupView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateGroupView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailGroupView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteGroupView.as_view(), name='delete'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', index, name='home'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

students/urls.py
from django.urls import path

from students.views import create_student_view
from students.views import ListStudentView
from .views import detail_student
from .views import delete_student

from .views import UpdateStudentView

app_name = 'students'

urlpatterns = [
    path('', ListStudentView.as_view(), name='list'),                       # students:list      group:list
    path('create/', create_student_view, name='create'),       # students/create/
    path('update/<int:pk>/', UpdateStudentView.as_view(), name='update'),
    path('detail/<int:pk>/', detail_student, name='detail'),
    path('delete/<int:pk>/', delete_student, name='delete'),
]

teachers/urls.py
from django.urls import path

from .views import ListTeacherView
from .views import UpdateTeacherView
from .views import CreateTeacherView
from .views import DeleteTeacherView
from .views import DetailTeacherView

app_name = 'teachers'

urlpatterns = [
    path('', ListTeacherView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateTeacherView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailTeacherView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteTeacherView.as_view(), name='delete')
]

students/models.py
from random import choice

from django.db import models

from core.models import PersonModel
from groups.models import Group


class Student(PersonModel):
    phone = models.CharField(max_length=25) #, null=True
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, related_name='students')

    class Meta:
        db_table = 'students'

    def __str__(self):
        if self.group:
            return f'{self.first_name} {self.last_name}({self.group.group_name})'
        else:
            return f'{self.first_name} {self.last_name}()'

    @classmethod
    def _generate(cls):
        groups = Group.objects.all()
        student = super()._generate()
        student.group = choice(groups)
        student.save()

students/forms.py
from django import forms
from django_filters import FilterSet
from students.models import Student


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'email',
            'city',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def clean_first_name(self):
        value = self.cleaned_data.get('first_name')
        return value.capitalize()


    def clean_phone(self):
        value = self.cleaned_data.get('phone')
        new_value = ''
        symbols = ['+', '-', '(', ')']
        for i in value:
            if i.isnumeric() or i in symbols:
                new_value += i
        return new_value


class UpdateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'city',
            'phone',
            'group'
        ]
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }


class StudentFilterForm(FilterSet):
    class Meta:
        model = Student
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith']
        }

students/views.py
from copy import copy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import UpdateView, ListView
from django.urls import reverse, reverse_lazy

from .forms import CreateStudentForm, UpdateStudentForm, StudentFilterForm
from .models import Student


class ListStudentView(ListView):
    model = Student
    template_name = 'students/list.html'
    paginate_by = 10

def get_filter(self):
    students = Student.objects.all().order_by('birthday').select_related('group', 'headman_group')
    filter_form = StudentFilterForm(data=self.request.GET, queryset=students)
    return filter_form

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_filter().form
        params = self.request.GET
        if 'page' in params:
            params = copy(params)
            del params['page']
        context['params'] = f'&{params.urlencode()}' if params else ''
        return context


@login_required
def create_student_view(request):
    if request.method == 'GET':
        form = CreateStudentForm()
    elif request.method == 'POST':
        form = CreateStudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))

    return render(request, 'students/create.html', {'form': form})


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = UpdateStudentForm
    success_url = reverse_lazy('students:list')
    template_name = 'students/update.html'


@login_required
def detail_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    return render(request, 'students/detail.html', {'student': student})


@login_required
def delete_student(request, pk):
    st = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        st.delete()
        return HttpResponseRedirect(reverse('students:list'))
    return render(request, 'students/delete.html', {'student': st})

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg fixed-top" style="background-color: #e3f2fd;">
  <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Student
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'students:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'students:create' %}">Create</a></li>
                        {% endif %}
                    </ul>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Group
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'groups:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'groups:create' %}">Create</a></li>
                        {% endif %}
                    </ul>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Teacher
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'teachers:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'teachers:create' %}">Create</a></li>
                        {% endif %}
                    </ul>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Course
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'courses:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                          <li><a class="dropdown-item" href="{% url 'courses:create' %}">Create</a></li>
                        {% endif %}
                    </ul>

            </ul>
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                            {% else %}
                                User
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign Out</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Sign Up</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Sign In</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'password_reset' %}">Reset password</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
  </div>
</nav>

templates/includes/paginator.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ params }}"><i class="bi bi-chevron-double-left"></i></a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ params }}"><i class="bi bi-chevron-left"></i></a>
            </li>

        {% else %}
            <li class="page-item disabled">
                <a class="page-link"><i class="bi bi-chevron-double-left"></i></a>
            </li>
            <li class="page-item disabled">
                <a class="page-link"><i class="bi bi-chevron-left"></i></a>
            </li>

        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item"><a class="page-link active">{{ num }}</a></li>
            {% elif not page_obj.has_previous and num < page_obj.number|add:5 %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{{ params }}">{{ num }}</a></li>
            {% elif page_obj.number == 2 and num < page_obj.number|add:4 %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{{ params }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{{ params }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:-4 and page_obj.number == page_obj.paginator.num_pages|add:-1 %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{{ params }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:-5 and not page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{{ params }}">{{ num }}</a></li>

            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{{ params }}"><i
                        class="bi bi-chevron-right"></i></a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{ params }}"><i
                        class="bi bi-chevron-double-right"></i></a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link"><i class="bi bi-chevron-right"></i></a>
            </li>
            <li class="page-item disabled">
                <a class="page-link"><i class="bi bi-chevron-double-right"></i></a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/includes/students_table.html
<table class="table table-striped table-hover">
    <thead>
    <tr class="text-center">
        <th></th>
        <th>First name</th>
        <th>Last name</th>
        <th>Birthday</th>
        <th>Headman</th>
        {% if not is_group %}
            <th>Group</th>
             {% if user.is_authenticated %}
                <th><i class="bi bi-pencil-square"></i></th>
                <th><i class="bi bi-trash3"></i></th>
             {% endif %}
        {% endif %}
    </tr>
    <thead>
    <tbody>
    {% for st in object_list %}
        <tr>
            <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
            {% if user.is_authenticated %}
                <td><a href="{% url 'students:detail' st.pk %}">{{ st.first_name }}</a></td>
            {% else %}
                <td>{{ st.first_name }}</td>
            {% endif %}
            <td>{{ st.last_name }}</td>
            <td class="text-center">{{ st.birthday|date:'d M Y (l)' }}</td>
            <td class="text-center">
                {% if st.headman_group %}
                    <i class="bi bi-check2-circle"></i></td>
                {% endif %}
            {% if not is_group %}
                <td class="text-center">{{ st.group.group_name }}</td>
                {% if user.is_authenticated %}
                    <td class="text-center"><a class="btn btn-outline-primary btn-sm"
                                               href="{% url 'students:update' st.pk %}">Edit</a></td>
                    <td class="text-center"><a class="btn btn-outline-danger btn-sm"
                                               href="{% url 'students:delete' st.pk %}">Remove</a></td>
                {% endif %}
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>