courses/urls.py
from django.urls import path

from .views import ListCourseView
from .views import CreateCourseView
from .views import UpdateCourserView
from .views import DetailCourseView
from .views import DeleteCourseView

app_name = 'courses'

urlpatterns = [
    path('', ListCourseView.as_view(), name='list'),
    path('create/', CreateCourseView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateCourserView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailCourseView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteCourseView.as_view(), name='delete'),

]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', index, name='home'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

courses/models.py
import random

from django.db import models

from core.models import BaseModel
from groups.models import Group
from teachers.models import Teacher


class Course(BaseModel):
    course_name = models.CharField(max_length= 20, verbose_name='Course name', db_column='c_name')
    program = models.TextField(null=True, blank=True)
    course_price = models.CharField(max_length=20)

    class Meta:
        db_table = 'courses'

    def __str__(self):
        return f'{self.course_name}'

    @classmethod
    def generate_fake_data(cls, cnt):
        course_name = ['Beginner', 'Middle', 'Advanced']
        for _ in range(cnt):
            s = cls()
            s.course_name = f'{random.choice(course_name)}'
            s.save()

courses/forms.py
from django import forms
from django_filters import FilterSet

from courses.models import Course


class CourseBaseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = [
            'course_name',
            'program',
            'course_price'
        ]


class CreateCourseForm(CourseBaseForm):
    class Meta(CourseBaseForm.Meta):
        pass


class UpdateCourseForm(CourseBaseForm):
    class Meta(CourseBaseForm.Meta):
        pass


class CourseFilterForm(FilterSet):
    class Meta:
        model = Course
        fields = {
            'course_name': ['exact', 'icontains']
        }

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from courses.forms import CreateCourseForm, UpdateCourseForm, CourseFilterForm
from courses.models import Course


class ListCourseView(ListView):
    model = Course
    template_name = 'courses/list.html'

    def get_queryset(self):
        courses = Course.objects.all().order_by('course_name')
        filter_form = CourseFilterForm(data=self.request.GET, queryset=courses)
        return filter_form


class CreateCourseView(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CreateCourseForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/create.html'


class UpdateCourserView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = UpdateCourseForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/update.html'


class DetailCourseView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courses/detail.html'


class DeleteCourseView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = 'courses/delete.html'
    success_url = reverse_lazy('courses:list')

courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create course{% endblock %}


{% block content %}
        <div class='row'>
            <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="text-center">
                        <input class="btn btn-outline-success" type="submit" value="Create">
                        <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                    </div>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
{% endblock %}

courses/templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}Delete course{% endblock %}

{% block content %}
        <div class='row'>
            <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <p>Do you want to delete course <strong>{{ course.course_name }}</strong>?</p>
                        <input class="btn btn-outline-success" type="submit" value = 'Agree'>
                        <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                    </div>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
{% endblock %}

courses/templates/courses/detail.html
{% extends 'base.html' %}

{% block title %}Course details{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col align-self-center">
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">{{ course.course_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Price: {{ course.course_price }}</h6>
                {% if course.course_program %}<p class="card-text">Program: {{ course.program }}</p>{% endif %}
                <div class="text-center">
                    <a class="btn btn-outline-primary" href="{% url 'courses:update' course.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
              </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

courses/templates/courses/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Courses list{% endblock %}

{% block content %}
    <div class="row">
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        Search
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                     data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <div class="col-3"></div>
                        <div class="col">
                            <form method="get">
                                {{ object_list.form|crispy }}
                                <input class="btn btn-outline-success" type="submit" value="Search"><br>
                            </form>
                        </div>
                        <div class="col-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
            <tr class="text-center">
                <th></th>
                <th>Course Name</th>
                <th>Price</th>
                {% if user.is_authenticated %}
                    <th><i class="bi bi-pencil-square"></i></th>
                    <th><i class="bi bi-trash3"></i></th>
                {% endif %}
            </tr>
            <thead>
            <tbody>
            {% for course in object_list.qs %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'courses:detail' course.pk %}">{{ course.course_name }}</a></td>
                     {% else %}
                        <td>{{ course.course_name }}</td>
                    {% endif %}
                    <td class="text-center">{{ course.program }}</td>
                    {% if user.is_authenticated %}
                        <td class="text-center"><a class="btn btn-outline-primary btn-sm"
                                               href="{% url 'courses:update' course.pk %}">Edit</a></td>
                        <td class="text-center"><a class="btn btn-outline-danger btn-sm"
                                               href="{% url 'courses:delete' course.pk %}">Remove</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

courses/templates/courses/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Course update "{{ course.course_name }}"
{% endblock %}

{% block content %}
    <div class='row'>
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-success" type="submit" value="Update">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}